DROP TABLE IF EXISTS roster;
DROP TABLE IF EXISTS titles;
DROP TABLE IF EXISTS associations;
DROP TABLE IF EXISTS companies;
DROP TABLE IF EXISTS result;
DROP TABLE IF EXISTS match_types;
DROP TABLE IF EXISTS fueds;


CREATE TABLE roster (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name TEXT NOT NULL,
    real_name TEXT NOT NULL,
    role TEXT NOT NULL,
    association TEXT NOT NULL,
    accolade TEXT NOT NULL,
    active TEXT NOT NULL,
    finisher TEXT NOT NULL,
    attack TEXT NOT NULL,
    defense TEXT NOT NULL,
    health TEXT NOT NULL,
    level TEXT NOT NULL,
    wins TEXT NOT NULL,
    losses TEXT NOT NULL,
    img TEXT NOT NULL
);

CREATE TABLE fueds (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    participant_1 TEXT NOT NULL,
    participant_2 TEXT NOT NULL,
    popularity TEXT NOT NULL,
    status TEXT NOT NULL,
    company TEXT NOT NULL
);

CREATE TABLE titles (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    association TEXT NOT NULL,
    img TEXT NOT NULL
);


CREATE TABLE result (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    result TEXT NOT NULL,
    description TEXT NOT NULL,
    rating int NOT NULL
);

CREATE TABLE match_types (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name TEXT NOT NULL
);

CREATE TABLE companies (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name TEXT NOT NULL,
    img TEXT NOT NULL
);